site_name: rcppspdlog
site_url: https://github.com/eddelbuettel/rcppspdlog
docs_dir: src
site_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - tabs
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/rcppspdlog

nav:
  - Home:
    - index.md
  - Reference:
    - man/RcppSpdlog-package.md
    - man/exampleRsink.md
    - man/setLogLevel.md
  - Articles:
     - Introduction: vignette/introduction.md
  - News:
     - news.md
  - Changelog:
    - changelog.md
