site_name: rcppspdlog
site_url: https://github.com/eddelbuettel/rcppspdlog
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2020 - present Dirk Eddelbuettel
repo_url: https://github.com/eddelbuettel/rcppspdlog
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/rcppspdlog
      name: rcppspdlog on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eddelbuettel
      name: eddelbuettel on Twitter

nav:
  - Home:
    - index.md
  - Reference:
    - man/RcppSpdlog-package.md
    - man/exampleRsink.md
    - man/setLogLevel.md
    - man/log_setup.md
  - Articles:
     - Introduction: vignette/introduction.md
  - News:
     - news.md
  - Changelog:
    - changelog.md
